import EQUIPOS from "./equipos";
const PARTIDOS = [
  {
    id: 1,
    titulo: "CentroSur de Damas Juniors",
    equipo1: EQUIPOS.find((eq) => eq.nombre === "Club Mendoza de Regatas"),
    equipo2: EQUIPOS.find((eq) => eq.nombre === "Universidad Nacional de Cuyo"),
    categoria: "Juvenil Masculino",
    sede: "Polideportivo Ribosqui",
    fecha: "Domingo 14 de mayo",
    torneo: "Apertura 2022",
    jornada: "Fecha 5",
    resultado: {
      total_str: "24 - 22",
      final_eq1: "24",
      final_eq2: "22",
      parcial_eq1: "11",
      parcial_eq2: "11",
    },
  },
  {
    id: 2,
    titulo: "Competencias de la CAH",
    equipo1: EQUIPOS.find((eq) => eq.nombre === "Club Mendoza de Regatas"),
    equipo2: EQUIPOS.find((eq) => eq.nombre === "Universidad Nacional de Cuyo"),
    categoria: "Juvenil Masculino",
    sede: "Polideportivo Ribosqui",
    fecha: "Domingo 14 de mayo",
    torneo: "Apertura 2022",
    jornada: "Fecha 5",
    resultado: {
      total_str: "24 - 22",
      final_eq1: "24",
      final_eq2: "22",
      parcial_eq1: "11",
      parcial_eq2: "11",
    },
  },
  {
    id: 3,
    titulo: "Convocados Preseleccion Juveniles",
    equipo1: EQUIPOS.find((eq) => eq.nombre === "Club Mendoza de Regatas"),
    equipo2: EQUIPOS.find((eq) => eq.nombre === "Universidad Nacional de Cuyo"),
    categoria: "Juvenil Masculino",
    sede: "Polideportivo Ribosqui",
    fecha: "Domingo 14 de mayo",
    torneo: "Apertura 2022",
    jornada: "Fecha 5",
    resultado: {
      total_str: "24 - 22",
      final_eq1: "24",
      final_eq2: "22",
      parcial_eq1: "11",
      parcial_eq2: "11",
    },
  },
  {
    id: 4,
    titulo: "5ta Fecha Apertura",
    equipo1: EQUIPOS.find((eq) => eq.nombre === "Club Mendoza de Regatas"),
    equipo2: EQUIPOS.find((eq) => eq.nombre === "Universidad Nacional de Cuyo"),
    categoria: "Juvenil Masculino",
    sede: "Polideportivo Ribosqui",
    fecha: "Domingo 14 de mayo",
    torneo: "Apertura 2022",
    jornada: "Fecha 5",
    resultado: {
      total_str: "24 - 22",
      final_eq1: "24",
      final_eq2: "22",
      parcial_eq1: "11",
      parcial_eq2: "11",
    },
  },
  {
    id: 5,
    titulo: "Jugadoras de Maipu en la seleccion",
    equipo1: "Regatas",
    equipo2: "",
    categoria: "Juvenil Masculino",
    sede: "Polideportivo Ribosqui",
    fecha: "Domingo 14 de mayo",
    torneo: "Apertura 2022",
    jornada: "Fecha 5",
    resultado: {
      total_str: "24 - 22",
      final_eq1: "24",
      final_eq2: "22",
      parcial_eq1: "11",
      parcial_eq2: "11",
    },
  },
];

export default PARTIDOS;
